#+TITLE: Networked Collaborative Performance
#+SUBTITLE: Frugal Strategies and Cultural Impact of Technology

* Introductory Statement

The integration of technologies such as internet communication and collaboration tools, devices for human machine-interaction, live audiovisual media processing and live coding of performance, has led to the emergence of new fields of creativity in performance arts. Such "art/technology, dance/technology and new media art—the cross-over performance and science assemblages'' (Birringer 2016:8), give rise to the premise of "bodily motion and non-verbal communication, understood as changing repertoires of emotional expression and cognition, constitute a foundation of sustainable cultural diversity, a changing matrix of embodied knowledge in permanent formation" (Birringer 2016: 18).  At the same time, this body-focused approach is complemented by projects and communities such as the Algorithmic Pattern Catalogue by Alex McLean (https://algorithmicpattern.org/) and the live coding community (https://toplap.org/). As these technologies are maturing and becoming more widely accessible to different social groups in various countries, it is needed to assess their impact in social processes through the building of cultural narratives or through the creation of means for the recording, study, transmission and transmutation of cultural practices  (See for example recent calls by the Journals Performance Philosophy and ECHO). As open-source software and human-machine-interaction hardware become more accessible, more culturally diverse groups put them to artistic uses. However, collaboration across cultural and disciplinary borders poses a host of problems not just of technical but also of cultural communication. In this context, the proposed panel investigates the impact of internet collaboration with live coding and other live interaction technologies on culture and the new kinds of art forms that arise from it, especially under the perspective of frugal innovation, i.e. the combination of technical skills, economy of means and an intuitive approach to technology. The premise that this panel ultimately intends to raise as a challenge, is that such work requires a global approach on the technical, organizational, social and cultural aspects in order to be sustainable. As Birringer states, technology is inseparable from the social. In the field of interactive performance arts, this gains particular significance, because of the fragile and crucial role that communication plays in the collaborative creative process. The objective of the panel is to illuminate the different aspects of this field, technological, aesthetic, social and philosophical, to show from their own perspectives how all of these aspects are interrelated, and to identify the central challenges and strategies involved in creative collaboration and research in this field. To this purpose, the panel brings together artists, technologists and educators that approach this topic from different perspectives in order to report their experience as practitioners and to discuss how the combination of these technologies changes the way in which we collaborate in these cross-over performance and science assemblages. Each panelist is asked to report on related aspects in their recent work, from the perspective of their practical experience, and giving examples from their own work.

* Panelist Statements
** Iannis Zannos
Open source software and a rhizomatic bottom-up approach to artistic creation can help boost creativity and innovation through networked collaboration.  As Vilém Flusser and Friedrich Kittler have noted, recorded image and sound have already been added along with text as carriers of meaning in contemporary technological culture. The increased availability of open source software and hardware as well as online tools for sharing knowledge related to these technologies, coupled with the proliferation of technologies for sensing our environments and bodies through measurement devices open up the promise of integrating program code and its logic-mathematical substratum into these cultural creative processes. Sharing real-time performance practices involving sensors with data over the internet can play a key role in effecting this transition and help widen the cultural semiotic horizon beyond text-sound-image and onto code and abstract forms. Collaborative performance of the internet creates new virtual space where these aspects can be integrated and new meaning-generating mechanisms can arise. This inevitably leads to new kinds of communities that re-interpret given contexts and go beyond traditional identity barriers. 

** Jean-Francois Jégo
The concept of frugal innovation invites us to rethink the complexity and cost of the creation process in digital arts (Jego et George-Molland, 2021). Frugal innovation is combining both technical skill, economy of means and a naive and intuitive approach (Qadir et al. 2016). It can be currently observed in developing countries and in third places of creation such as fablabs or makerlabs. This approach based on principles of inclusiveness refers to the notions of autonomy, tailor-made, sustainability and common goods. It is also echoing the practices of the Do-It-Yourself community: for example, the Jerry Do-It-Together is a computer assembled from a plastic container and computer components from waste electronic equipment. It gives a second life to this accessible material while making the means of communication and digital creation available to as many people as possible. Developed during collective workshops including stages of personalisation and decoration, these “personal” computers make it possible to restore the singularity to the technical tool, and thus give it an integrated affective value. This reminds that some artists, even before creating, shape their tools, become attached to them, and thus accentuate their durability. We will discuss how networked collaborative performance can benefit from and contribute to the frugal innovation movement.

** Peter Nelson
Taking the Pragmatist view in which living selves present as bundles of habit (James), and acknowledging both the contributions of habit to 4E Cognition, and the social implications of this view developed by Bourdieu in his notion of the habitus, this contribution considers and compares the notions of habit and algorithm in order to interrogate new methods of habit formation and creative process evident within contemporary digital art practices.
 
** Johannes Birringer
The panelist will report on their collaborative technical / soma-technical practice of the past few years, which encompasses a cross-cultural method (involving movement, drawing, transcribing physical/virtual narration and image-sound-wearable design, working with found and made objects in real space as well as telepresence space) of finding pathways for a better social understanding of creative re-embodiment and conjoining temporarily abled bodies.

** Pavlos Antoniadis
The democratisation of interactive internet- and web-based technologies expands the traditional communicative networks in music. Whether in terms of micro- or macro-communication, ranging from the sophisticated interplay between improvisers to mass media cultural industries, these networks are radically decomposed and rethought in terms of technologically mediated categories such as presence, immersion, augmentation, interaction (Chris Salter). In this panel discussion, I will reflect on the role of musical embodiment as a site of frugal innovation and social interaction, through its rendition into multimodal data via sensor technologies and communication protocols. This rendering is often thought of in terms of control and command metaphors, bearing a military origin (Marije Baalman): control of input gesture, commands of output media and so on. In light of the biopolitics of cognitive capitalism (Yann Moulier-Boutang), this rendering becomes even more politically charged, relating to the collapse of two traditional Foucauldian categories (personal and population control) into massive surveillance of intimate performance data (Shoshanna Zuboff). Inspired by Brian Massumi’s take on Gregory Bateson, I will attempt to propose an alternative model, whereby the notion of animal play as abstraction and metacommunication informs the development of a new biopolitical paradigm for Human-Machine Interaction in music. I will be reporting case studies of ludic exploration, non-verbal self-reflexivity, prelinguistic emergence, hacking and détournement, accentuating the potential of these technologies for collective creativity, political sensegiving and critical distancing in today’s musicking. 

** Stella Paschalidou
[Panelist 4 Statement:] My panel contribution will be focusing on aspects of remote music education during and after the pandemic, which relies on domestically available frugal technologies (such as simple web cameras and personal computers) and is enabled through non-music-specific network collaboration platforms. I will open a discussion on the effect this might have had on oral music traditions (in specific Hindustani music), i.e. traditions in which the transmission of knowledge does not rely (at least exclusively) on written notation, but is succeeded through aural, oral and visual means in face-to-face sessions between teacher and student and includes the transmission of a set of bodily dispositions too.

** Haruka Hirayama
I will discuss my experience as composer through experiments with intermedia performance forms that involve collaborations with dancers and actors, focussing on the challenges of integrating sensors and other technical media into my work and of forming pieces within a setting of networked collaboration. 

** Dana Papachristou
[Panelist 6 Statement:] My contribution in the proposed panel will treat the convergence of technology and the human body for artistic purposes combining the fields of Performance Studies, Media Studies and the Arts. Starting from various artistic works that use motion sensors and telematic technologies, I will draw upon new media possibilities and artistic practices so as to analyse the relation between the technical and the human in contemporary performative arts. These new available technologies not only create a condition for processing, recording, producing or enhancing physical techniques, but also assist in transforming physical practices and establishing new human-machine spheres. Technology, linked to humans from the beginning of their existence, becomes a global medium created by them which also radically alters them, making it impossible to distinguish the boundary between "the empire of man and the kingdom of technique" (Latour). Thus, the human-technology distinction is unfounded (Simondon), while the position that humans invent while the technological tool is invented has become obsolete (Stiegler). At the same time, conditions are created in which technology can - and must - function as a space for political and social action (Galloway and Thacker). My main interest is how do these prerequisites apply into the artistic practices, and more specifically in dance and music performances with sensor motions.

* Questions
 
** Main Question
Can networked performance form an alternative tool for creating narratives? What narratives exist in (collaborative, networked) intermedia performance and how do they relate to traditional cultural narratives presented through other media?
** Subsidiary questions

- Can technology and the internet be used as creative tools by communities irrespectively of differences in economical, social, and educational status, and if so, how?  What is the potential of such projects to affect change in various societies? How can this potential be enhanced or and its effects appreciated? 
- How does collaboration affect your work as an artist? How does it influence your choice of topics and approaches in your work?
- What kinds of art forms and formal structures arise from networked interactive performance and how do they relate to established art forms and structures?
- How does collaborative art research relate to frugal approaches in innovation and technology? What are the contributions of frugal approaches from non-central, local communities to mainstream technology and art?
