#+TITLE: Readme

ISEA23 panel

#+begin_example
Presentation Date: May 18, 2023, 10:20 am
Forum des Images
Room 100
#+end_example

The integration of technologies such as internet communication and collaboration tools, devices for human machine-interaction, live audiovisual media processing and live coding of performance, has led to the emergence of new fields of creativity in performance arts. Such "art/technology, dance/technology and new media art—the cross-over performance and science assemblages'' (Birringer 2016:8), give rise to the premise of "bodily motion and non-verbal communication, understood as changing repertoires of emotional expression and cognition, constitute a foundation of sustainable cultural diversity, a changing matrix of embodied knowledge in permanent formation" (Birringer 2016: 18).  At the same time, this body-focused approach is complemented by projects and communities such as the Algorithmic Pattern Catalogue by Alex McLean (https://algorithmicpattern.org/) and the live coding community (https://toplap.org/). As these technologies are maturing and becoming more widely accessible to different social groups in various countries, it is needed to assess their impact in social processes through the building of cultural narratives or through the creation of means for the recording, study, transmission and transmutation of cultural practices  (See for example recent calls by the Journals Performance Philosophy and ECHO). As open-source software and human-machine-interaction hardware become more accessible, more culturally diverse groups put them to artistic uses. However, collaboration across cultural and disciplinary borders poses a host of problems not just of technical but also of cultural communication. In this context, the proposed panel investigates the impact of internet collaboration with live coding and other live interaction technologies on culture and the new kinds of art forms that arise from it, especially under the perspective of frugal innovation, i.e. the combination of technical skills, economy of means and an intuitive approach to technology. The premise that this panel ultimately intends to raise as a challenge, is that such work requires a global approach on the technical, organizational, social and cultural aspects in order to be sustainable. As Birringer states, technology is inseparable from the social. In the field of interactive performance arts, this gains particular significance, because of the fragile and crucial role that communication plays in the collaborative creative process. The objective of the panel is to illuminate the different aspects of this field, technological, aesthetic, social and philosophical, to show from their own perspectives how all of these aspects are interrelated, and to identify the central challenges and strategies involved in creative collaboration and research in this field. To this purpose, the panel brings together artists, technologists and educators that approach this topic from different perspectives in order to report their experience as practitioners and to discuss how the combination of these technologies changes the way in which we collaborate in these cross-over performance and science assemblages. Each panelist is asked to report on related aspects in their recent work, from the perspective of their practical experience, and giving examples from their own work.
